### ISSUE TITLE
如何收集的影神图资料

### ISSUE THREAD

**Issue by w5han** [STDquantum/yingshentu#2]
您好, 我想请教一下怎么收集到的影神图的图文资料.
我自己先前通过搜索引擎获取到的都有残缺,  浪费了不少时间, 所以真心提问请教一下您搜集资料的方法和过程 @STDquantum

**Comment by STDquantum** [comment]
b站搜一下黑神话解包就行，比如dauercom的教程就能用。他还发了资产检索，在里面可以找到影神图的相关源文件和文本，我这个代码就是对源文件进行了一些处理

**Comment by w5han** [comment]
非常感谢,  我之前在B站直接搜影神图资料, 然后下载的是别人二次整理过的, 用起来不太合适. 您提供的思路搜解包资源或解包方法对我以后搜集资料都很有启发, 谢谢
